#
# This YAML file defines the multi-container infrastructure for
# running this application in production. Common commands are:
#    docker-compose build
#    docker-compose up
#
# https://docs.docker.com/compose/
#

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - 8000
      - 8001:8001
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    depends_on:
      - app
    ports:
      - 80:80
