#
# This dockerfile builds and runs the frontend proxy
#

# Use Nginx on Alpine Linux as the base
FROM nginx:1.13.7-alpine

# Make ports available to the world
EXPOSE 80

# Add the config file
RUN rm -v /etc/nginx/conf.d/default.conf
COPY ./deploy/nginx.conf /etc/nginx/conf.d/nginx.conf
